name: Update Global Config

on:
  schedule:
    - cron:  '22 2 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install libpcap libappindicator3-1
      run: sudo apt-get install libpcap-dev libappindicator3-1
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Granting private modules access
      run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
    - name: Execute refreshGlobalConfig script
      run: |
        refreshGlobalConfig.bash
