name: Update Global Config

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Granting private modules access
      run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
    - uses: actions/checkout@v2
      with:
        ref: devel
    - run: |
        curl https://globalconfig.flashlightproxy.com/global.yaml.gz | gunzip >> yaml-temp
        echo 'package generated' > ./config/generated/embeddedGlobal.go
        echo '' >> ./config/generated/embeddedGlobal.go
        echo 'var GlobalConfig = []byte(`' >> ./config/generated/embeddedGlobal.go
        cat yaml-temp >> ./config/generated/embeddedGlobal.go
        echo '`)' >> ./config/generated/embeddedGlobal.go
        rm yaml-temp
        cd ./config
        go test -run TestGlobal
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add generated/embeddedGlobal.go
        git commit -m "pushing auto-generated embedded global config"
        echo "pushing to devel"
        git push origin devel
