name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install libpcap
      run: sudo apt-get install lsof libpcap-dev libappindicator3-dev libwebkit2gtk-4.0-dev
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Granting private modules access
      run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
    - name: Build
      run: HEADLESS=true make lantern

    #- name: Test
     # run: go test -v ./...

    - name: Run Unit tests
      run: |
        go test -race -failfast -tags="headless" -covermode atomic -coverprofile=profile.cov ./...

    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=profile.cov -service=github
