addr: 127.0.0.1:8787
autoLaunch: true
autoReport: true
language: en-US
localHTTPToken: ""
pacURL: ""
proxyAll: false
socksAddr: 127.0.0.1:8788
systemProxy: true
uiAddr: localhost:16823
userID: 114847235
userToken: MK5wK2_c5yu9lwFhB44tXd-SH4KB4d0d286DCA_a6qEiRkK7lBY4aw
